// AUTO-GENERATED by tools/build_data.py from research/data/*.csv. Do not edit.
export const scores = {
 "FIN": {
  "math": {
   "2003": 544,
   "2006": 548,
   "2009": 541,
   "2012": 519,
   "2015": 511,
   "2018": 507,
   "2022": 484,
   "2025": 469
  },
  "reading": {
   "2006": 547,
   "2018": 520,
   "2022": 490,
   "2025": 474
  },
  "science": {
   "2006": 563,
   "2022": 511,
   "2025": 504
  }
 },
 "EST": {
  "math": {
   "2006": 515,
   "2009": 512,
   "2012": 521,
   "2015": 520,
   "2018": 523,
   "2022": 510,
   "2025": 508
  },
  "reading": {
   "2006": 501,
   "2009": 501,
   "2012": 516,
   "2015": 519,
   "2018": 523,
   "2025": 499
  },
  "science": {
   "2006": 531,
   "2009": 528,
   "2012": 541,
   "2015": 534,
   "2018": 530,
   "2022": 526,
   "2025": 527
  }
 },
 "JPN": {
  "math": {
   "2025": 525
  },
  "reading": {
   "2025": 503
  },
  "science": {
   "2025": 538
  }
 },
 "USA": {
  "math": {
   "2025": 463
  },
  "reading": {
   "2025": 490
  }
 },
 "GBR": {
  "science": {
   "2025": 511
  }
 },
 "OECD": {
  "math": {
   "2025": 463,
   "2022": 472
  },
  "reading": {
   "2025": 461
  },
  "science": {
   "2025": 482
  }
 }
} as const;
export const shares = {
 "FIN": {
  "top_performers_L5plus": {
   "2003": 23.0,
   "2025": 7.0
  },
  "low_performers_belowL2": {
   "2006": 7.0,
   "2022": 25.0
  }
 }
} as const;
export const facts: Record<string, {value: number; status: string; source: string}> = {
 "F-FIN-M-2003": {
  "value": 544,
  "status": "search_confirmed",
  "source": "https://fordhaminstitute.org/national/commentary/rise-and-fall-finland-mania-part-two-why-did-scores-plummet"
 },
 "F-FIN-M-2006": {
  "value": 548,
  "status": "search_confirmed",
  "source": "https://fordhaminstitute.org/national/commentary/rise-and-fall-finland-mania-part-two-why-did-scores-plummet"
 },
 "F-FIN-M-2009": {
  "value": 541,
  "status": "search_confirmed",
  "source": "https://fordhaminstitute.org/national/commentary/rise-and-fall-finland-mania-part-two-why-did-scores-plummet"
 },
 "F-FIN-M-2012": {
  "value": 519,
  "status": "search_confirmed",
  "source": "https://fordhaminstitute.org/national/commentary/rise-and-fall-finland-mania-part-two-why-did-scores-plummet"
 },
 "F-FIN-M-2015": {
  "value": 511,
  "status": "search_confirmed",
  "source": "https://fordhaminstitute.org/national/commentary/rise-and-fall-finland-mania-part-two-why-did-scores-plummet"
 },
 "F-FIN-M-2018": {
  "value": 507,
  "status": "search_confirmed",
  "source": "https://fordhaminstitute.org/national/commentary/rise-and-fall-finland-mania-part-two-why-did-scores-plummet"
 },
 "F-FIN-M-2022": {
  "value": 484,
  "status": "search_confirmed",
  "source": "https://valtioneuvosto.fi/en/-/1410845/pisa-2022-performance-fell-both-in-finland-and-in-nearly-all-other-oecd-countries"
 },
 "F-FIN-M-2025": {
  "value": 469,
  "status": "search_confirmed",
  "source": "https://valtioneuvosto.fi/en/-/1410845/pisa-2025-students-in-finland-still-perform-well-above-oecd-average-in-science"
 },
 "F-FIN-R-2006": {
  "value": 547,
  "status": "search_confirmed",
  "source": "https://gpseducation.oecd.org/CountryProfile?primaryCountry=FIN&topic=PI&treshold=10"
 },
 "F-FIN-R-2018": {
  "value": 520,
  "status": "search_confirmed",
  "source": "https://gpseducation.oecd.org/CountryProfile?primaryCountry=FIN&topic=PI&treshold=10"
 },
 "F-FIN-R-2022": {
  "value": 490,
  "status": "search_confirmed",
  "source": "https://gpseducation.oecd.org/CountryProfile?primaryCountry=FIN&topic=PI&treshold=10"
 },
 "F-FIN-R-2025": {
  "value": 474,
  "status": "search_confirmed",
  "source": "https://valtioneuvosto.fi/en/-/1410845/pisa-2025-students-in-finland-still-perform-well-above-oecd-average-in-science"
 },
 "F-FIN-S-2006": {
  "value": 563,
  "status": "search_confirmed",
  "source": "https://gpseducation.oecd.org/CountryProfile?primaryCountry=FIN&topic=PI&treshold=10"
 },
 "F-FIN-S-2022": {
  "value": 511,
  "status": "search_confirmed",
  "source": "https://gpseducation.oecd.org/CountryProfile?primaryCountry=FIN&topic=PI&treshold=10"
 },
 "F-FIN-S-2025": {
  "value": 504,
  "status": "search_confirmed",
  "source": "https://valtioneuvosto.fi/en/-/1410845/pisa-2025-students-in-finland-still-perform-well-above-oecd-average-in-science"
 },
 "F-EST-M-2006": {
  "value": 515,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-M-2009": {
  "value": 512,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-M-2012": {
  "value": 521,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-M-2015": {
  "value": 520,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-M-2018": {
  "value": 523,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-M-2022": {
  "value": 510,
  "status": "search_confirmed",
  "source": "https://www.oecd.org/en/publications/pisa-2022-results-volume-i-and-ii-country-notes_ed6fbcc5-en/estonia_dafed886-en.html"
 },
 "F-EST-M-2025": {
  "value": 508,
  "status": "search_confirmed",
  "source": "https://news.err.ee/1610131807/estonia-ranks-among-top-countries-in-latest-pisa-results"
 },
 "F-EST-R-2006": {
  "value": 501,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-R-2009": {
  "value": 501,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-R-2012": {
  "value": 516,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-R-2015": {
  "value": 519,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-R-2018": {
  "value": 523,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-R-2025": {
  "value": 499,
  "status": "search_confirmed",
  "source": "https://news.err.ee/1610131807/estonia-ranks-among-top-countries-in-latest-pisa-results"
 },
 "F-EST-S-2006": {
  "value": 531,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-S-2009": {
  "value": 528,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-S-2012": {
  "value": 541,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-S-2015": {
  "value": 534,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-S-2018": {
  "value": 530,
  "status": "search_confirmed",
  "source": "https://documents.ncsl.org/wwwncsl/Education/Study-Group/5.%20EstoniaPISATrendsNCEE.pdf"
 },
 "F-EST-S-2022": {
  "value": 526,
  "status": "search_confirmed",
  "source": "https://www.oecd.org/en/publications/pisa-2022-results-volume-i-and-ii-country-notes_ed6fbcc5-en/estonia_dafed886-en.html"
 },
 "F-EST-S-2025": {
  "value": 527,
  "status": "search_confirmed",
  "source": "https://news.err.ee/1610131807/estonia-ranks-among-top-countries-in-latest-pisa-results"
 },
 "F-JPN-M-2025": {
  "value": 525,
  "status": "search_confirmed",
  "source": "https://www.oecd.org/en/publications/pisa-2025-results-volume-i-country-notes_2d4ff9ea-en/japan_cf203dac-en.html"
 },
 "F-JPN-R-2025": {
  "value": 503,
  "status": "search_confirmed",
  "source": "https://www.oecd.org/en/publications/pisa-2025-results-volume-i-country-notes_2d4ff9ea-en/japan_cf203dac-en.html"
 },
 "F-JPN-S-2025": {
  "value": 538,
  "status": "search_confirmed",
  "source": "https://www.oecd.org/en/publications/pisa-2025-results-volume-i-country-notes_2d4ff9ea-en/japan_cf203dac-en.html"
 },
 "F-USA-M-2025": {
  "value": 463,
  "status": "secondary_only",
  "source": "https://www.newsweek.com/map-shows-which-countries-outscore-us-in-reading-and-math-12416556"
 },
 "F-USA-R-2025": {
  "value": 490,
  "status": "secondary_only",
  "source": "https://www.newsweek.com/map-shows-which-countries-outscore-us-in-reading-and-math-12416556"
 },
 "F-GBR-S-2025": {
  "value": 511,
  "status": "secondary_only",
  "source": ""
 },
 "F-OECD-M-2025": {
  "value": 463,
  "status": "search_confirmed",
  "source": "https://www.oecd.org/en/about/news/press-releases/2026/09/pisa-2025-students-reading-and-mathematics-performance-declined-sharply-across-the-oecd.html"
 },
 "F-OECD-R-2025": {
  "value": 461,
  "status": "search_confirmed",
  "source": "https://www.oecd.org/en/about/news/press-releases/2026/09/pisa-2025-students-reading-and-mathematics-performance-declined-sharply-across-the-oecd.html"
 },
 "F-OECD-S-2025": {
  "value": 482,
  "status": "search_confirmed",
  "source": "https://www.oecd.org/en/about/news/press-releases/2026/09/pisa-2025-students-reading-and-mathematics-performance-declined-sharply-across-the-oecd.html"
 },
 "F-OECD-M-2022": {
  "value": 472,
  "status": "search_confirmed",
  "source": "https://yle.fi/a/74-20063678"
 },
 "F-FIN-TOP-2003": {
  "value": 23.0,
  "status": "search_confirmed",
  "source": "https://www.helsinkitimes.fi/themes/themes/education/29247-finland-s-pisa-scores-fall-again-in-reading-and-maths.html"
 },
 "F-FIN-TOP-2025": {
  "value": 7.0,
  "status": "search_confirmed",
  "source": "https://www.helsinkitimes.fi/themes/themes/education/29247-finland-s-pisa-scores-fall-again-in-reading-and-maths.html"
 },
 "F-FIN-LOW-2006": {
  "value": 7.0,
  "status": "search_confirmed",
  "source": "https://www.jyu.fi/en/news/pisa-2022-performance-fell-both-in-finland-and-in-nearly-all-other-oecd-countries"
 },
 "F-FIN-LOW-2022": {
  "value": 25.0,
  "status": "search_confirmed",
  "source": "https://www.jyu.fi/en/news/pisa-2022-performance-fell-both-in-finland-and-in-nearly-all-other-oecd-countries"
 }
};
