"""Generate a TypeScript data module from research CSVs so every on-screen number is traceable.

Usage: python3 tools/build_data.py episodes/01-finland
"""
import csv
import json
import sys

ep = sys.argv[1]
scores = {}
facts = {}
for r in csv.DictReader(open(f"{ep}/research/data/pisa_mean_scores.csv")):
    if r["status"] == "needs_primary":  # never render unverified values
        continue
    scores.setdefault(r["country"], {}).setdefault(r["subject"], {})[int(r["year"])] = int(r["mean_score"])
    facts[r["fact_id"]] = {"value": int(r["mean_score"]), "status": r["status"], "source": r["source_url"]}
shares = {}
for r in csv.DictReader(open(f"{ep}/research/data/pisa_proficiency_shares.csv")):
    shares.setdefault(r["country"], {}).setdefault(r["measure"], {})[int(r["year"])] = float(r["value_pct"])
    facts[r["fact_id"]] = {"value": float(r["value_pct"]), "status": r["status"], "source": r["source_url"]}

out = f"{ep}/remotion/data.gen.ts"
with open(out, "w") as f:
    f.write("// AUTO-GENERATED by tools/build_data.py from research/data/*.csv. Do not edit.\n")
    f.write(f"export const scores = {json.dumps(scores, indent=1)} as const;\n")
    f.write(f"export const shares = {json.dumps(shares, indent=1)} as const;\n")
    f.write(f"export const facts: Record<string, {{value: number; status: string; source: string}}> = {json.dumps(facts, indent=1)};\n")
print("wrote", out, len(facts), "facts")
